### ISSUE TITLE
Kamera

### ISSUE THREAD

**Issue by Luiggi33** [JanoDasHuhn/Der-Schulweg#3]
Die Kamera folgt meist nicht schnell genug dem Spieler, man kann deswegen nicht immer sehen wo man hingeht.

**Comment by JanoDasHuhn** [comment]
hoffe es ist so ok
![images](https://user-images.githubusercontent.com/90400307/143691277-bc4b24f7-dfb6-4d57-85f3-58d6d48f07ff.png)
